import { pgTable, serial, text, real, integer, boolean, timestamp, jsonb } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { bagsTable } from "./bags";
import { grindersTable } from "./equipment";
import { machinesTable } from "./equipment";
import { hopperRangeBaselinesTable, hoppersTable } from "./hopper";

export const shotsTable = pgTable("shots", {
  id: serial("id").primaryKey(),
  shotDate: text("shot_date").notNull(),
  bagId: integer("bag_id").references(() => bagsTable.id),
  bean: text("bean"),
  bag: text("bag"),
  grinderId: integer("grinder_id").references(() => grindersTable.id),
  machineId: integer("machine_id").references(() => machinesTable.id),
  hopperId: integer("hopper_id").references(() => hoppersTable.id),
  hopperRangeBaselineId: integer("hopper_range_baseline_id").references(() => hopperRangeBaselinesTable.id),
  bagLabel: text("bag_label"),
  daysSinceOpen: integer("days_since_open"),
  grindSetting: real("grind_setting"),
  grindTime: real("grind_time"),
  initialGrindWeight: real("initial_grind_weight"),
  totalOutput: real("total_output"),
  dose: real("dose"),
  timeAdj: real("time_adj"),
  topUpGrind: real("top_up_grind"),
  overGrindRemoved: real("over_grind_removed"),
  beanDelta: real("bean_delta"),
  grindWaste: real("grind_waste"),
  beansAdded: real("beans_added"),
  doseCorrectionType: text("dose_correction_type"),
  doseCorrection: real("dose_correction"),
  outputDelta: real("output_delta"),
  yield: real("yield"),
  ratio: text("ratio"),
  temperature: integer("temperature"),
  pourDelay: integer("pour_delay"),
  pourTime: integer("pour_time"),
  flowTime: integer("flow_time"),
  rating: real("rating"),
  preferenceRating: real("preference_rating"),
  ratingDifference: real("rating_difference"),
  avgWeightedRating: real("avg_weighted_rating"),
  rated: boolean("rated"),
  isForOthers: boolean("is_for_others"),
  isReference: boolean("is_reference").notNull().default(false),
  signatureShot: boolean("signature_shot"),
  sourShot: boolean("sour_shot"),
  boundaryShot: boolean("boundary_shot"),
  beanAchievement: text("bean_achievement").array(),
  drinkType: text("drink_type"),
  brewMethod: text("brew_method"),
  status: text("status"),
  shotClassification: text("shot_classification").array(),
  faultStatus: text("fault_status").array(),
  referenceType: text("reference_type"),
  expressionStyle: text("expression_style").array(),
  dailyDriverCount: integer("daily_driver_count"),
  includeInAnalysis: boolean("include_in_analysis").default(true),
  importantToIntelligence: boolean("important_to_intelligence"),
  intelligenceLessonType: text("intelligence_lesson_type").array(),
  notes: text("notes"),
  faultNotes: text("fault_notes"),
  bagOpenedDate: text("bag_opened_date"),
  // System Phase / Experiment — the machine/workflow *learning era* a shot
  // belongs to (Carl's Airtable-era concept). Deliberately distinct from
  // hopperPhase, which is a bean/hopper operating window. systemPhase is the
  // era number (1 = setup, 2 = baseline, 3 = timed-dose optimization, ...);
  // systemPhaseName is its user-defined name; experimentName is an optional
  // named test running *inside* that phase. All nullable, no backfill: no
  // historical System Phase field exists in any Airtable/CSV export.
  systemPhase: integer("system_phase"),
  systemPhaseName: text("system_phase_name"),
  experimentName: text("experiment_name"),
  hopperPhase: text("hopper_phase"),
  hopperFullness: real("hopper_fullness"),
  hopperPercent: real("hopper_percent"),
  hopperRange: text("hopper_range"),
  tasteZone: text("taste_zone"),
  zone: text("zone"),
  zoneScore: integer("zone_score"),
  tasteScore: integer("taste_score"),
  agreementPercent: real("agreement_percent"),
  flowScore: real("flow_score"),
  modelFlag: text("model_flag"),
  timeGap: integer("time_gap"),
  scaleZone: text("scale_zone"),
  flowDiagnostic: text("flow_diagnostic"),
  pourDelayWindow: text("pour_delay_window"),
  flowTimeWindow: text("flow_time_window"),
  flowTimeOffset: real("flow_time_offset"),
  driftDelta: real("drift_delta"),
  shotDriftStatus: text("shot_drift_status"),
  shotQualityScore: real("shot_quality_score"),
  shotTier: text("shot_tier"),
  perfectRangeFlag: text("perfect_range_flag"),
  driftWarning: text("drift_warning"),
  hopperZone: text("hopper_zone"),
  hopperDriftLink: text("hopper_drift_link"),
  hopperImpactScore: real("hopper_impact_score"),
  hopperCorrectionRule: text("hopper_correction_rule"),
  actionSuggestion: text("action_suggestion"),
  scaleCalibrationReminder: text("scale_calibration_reminder"),
  bagCalibrationReminder: text("bag_calibration_reminder"),
  calculation: text("calculation"),
  baselineUnaidedOutput: real("baseline_unaided_output"),
  baselineOutputDelta: real("baseline_output_delta"),
  actualDoseError: real("actual_dose_error"),
  hopperThresholdFlag: text("hopper_threshold_flag"),
  hopperBehaviour: text("hopper_behaviour"),
  hopperSeverity: text("hopper_severity"),
  topUpGap: real("top_up_gap"),
  topUpRecommendation: text("top_up_recommendation"),
  importFingerprint: text("import_fingerprint").unique(),
  grindAdjusted: text("grind_adjusted"),
  shotsLeftEst: real("shots_left_est"),
  finishedShot: boolean("finished_shot"),
  sensoryNotes: text("sensory_notes"),
  airtableRecordId: text("airtable_record_id").unique(),
  rawRow: jsonb("raw_row").$type<Record<string, unknown>>(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const insertShotSchema = createInsertSchema(shotsTable).omit({
  id: true,
  createdAt: true,
});

export type InsertShot = z.infer<typeof insertShotSchema>;
export type Shot = typeof shotsTable.$inferSelect;
